version : '8.3'

services:
  database:
    image : mysql
    environment:
      DATABASE_PORT : 3306
      MYSQL_ROOT_PASSWORD : root
      MYSQL_DATABASE : moviebuzz 
  backend:
    image: jashwanthgolla/jash-dev-project
    ports:
      - 9090:9090
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/moviebuzz
      SPRING_DATASOURCE_USERNAME : root
      SPRING_DATASOURCE_PASSWORD : root
    depends_on:
      - database  
    
       
      