version : '8.3'

services:
  database:
    image : mysql
    environment:
      DATABASE_PORT : 3306
      MYSQL_ROOT_PASSWORD : root
      MYSQL_DATABASE : movie-buzz 
  backend:
    image: jashwanthgolla/jash-dev-project
    ports:
      - 8090:8090
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/movie-buzz?autoReconnect=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME : root
      SPRING_DATASOURCE_PASSWORD : root
    depends_on:
      - database  
    
       
      